### ISSUE TITLE
Quick question about code_generation_lite vs code_generation

### ISSUE THREAD

**Issue by alat-rights** [LiveCodeBench/LiveCodeBench#31]
Hi! Love this benchmark.

It seems that [code_generation_lite](https://huggingface.co/datasets/livecodebench/code_generation_lite) is intended to be a curated subset of [code_generation](https://huggingface.co/datasets/livecodebench/code_generation).

However, when I loaded code_generation_lite, I noticed that it had 511 rows.
```python
>>> lcb_codegen = load_dataset("livecodebench/code_generation_lite", version_tag="release_v2", split="test")
>>> lcb_codegen
Dataset({
    features: ['question_title', 'question_content', 'platform', 'question_id', 'contest_id', 'contest_date', 'starter_code', 'difficulty', 'public_test_cases', 'private_test_cases', 'metadata'],
    num_rows: 511
})
```

Meanwhile, I notice that [code_generation](https://huggingface.co/datasets/livecodebench/code_generation) only has 400 rows.
```python
>>> ds = load_dataset("livecodebench/code_generation")
>>> ds
DatasetDict({
    test: Dataset({
        features: ['question_title', 'question_content', 'platform', 'question_id', 'contest_id', 'contest_date', 'starter_code', 'difficulty', 'public_test_cases', 'private_test_cases', 'metadata'],
        num_rows: 400
    })
})
```

I was wondering why this was, and whether it is still recommended to use code_generation_lite over code_generation.

I'm probably just being silly, but would love clarification!

Thanks.

**Comment by Naman-ntc** [comment]
Hi, yes the nomenclature is a bit funny but `code_generation_lite` was designed as a low-cost alternative for the original `code_generation` dataset by pruning the tests. Since then`code_generation_lite` has been updated as part of the second release of our "live" benchmark. Thus, it has more problems (511) against 400 in the first release. If you use `release_v1` version for `code_generation_lite`, you will notice the same 400 problems there as well
